create table subjects
(
    id   bigint not null generated by default as identity,
    name varchar(50),
    primary key (id),
    unique (name)
);
create table groups
(
    id   bigint not null generated by default as identity,
    name varchar(50),
    primary key (id),
    unique (name)
);
create table time
(
    id        bigint not null generated by default as identity,
    starttime time,
    endtime   time,
    primary key (id)
);
create table classrooms
(
    id   bigint not null generated by default as identity,
    name varchar(50),
    primary key (id),
    unique (name)
);
create table roles
(
    id   bigint not null generated by default as identity,
    name varchar(50),
    primary key (id),
    unique (name)
);
create table schedule
(
    id           bigint not null generated by default as identity,
    group_id     bigint,
    subject_id   bigint,
    day          smallint,
    time_id      bigint,
    classroom_id bigint,
    role_id      bigint,
    primary key (id),
    foreign key (group_id)
        references groups (id),
    foreign key (subject_id)
        references subjects (id),
    foreign key (time_id)
        references time (id),
    foreign key (classroom_id)
        references classrooms (id),
    foreign key (role_id)
        references roles (id)
);
create table users
(
    id   bigint not null generated by default as identity,
    name varchar(50),
    primary key (id)
);
create table user_role
(
    user_id bigint,
    role_id bigint,
    foreign key (user_id)
        references users,
    foreign key (role_id)
        references roles,
    primary key (user_id, role_id)
);
