create table subjects
(
    id   bigint not null generated by default as identity,
    name varchar(50),
    primary key (id),
    unique (name)
);
create table groups
(
    id   bigint not null generated by default as identity,
    name varchar(50),
    primary key (id),
    unique (name)
);
create table time
(
    id        bigint not null generated by default as identity,
    starttime time,
    endtime   time,
    primary key (id),
    unique (starttime),
    unique (endtime)
);
create table classrooms
(
    id   bigint not null generated by default as identity,
    name varchar(50),
    primary key (id),
    unique (name)
);
create table roles
(
    id   bigint not null generated by default as identity,
    name varchar(50),
    primary key (id),
    unique (name)
);
create table schedule
(
    id           bigint not null generated by default as identity,
    group_id     bigint references groups (id) on delete cascade,
    subject_id   bigint references subjects (id) on delete cascade,
    day          int,
    time_id      bigint references time (id) on delete cascade,
    classroom_id bigint references classrooms (id) on delete cascade
);
create table users
(
    id   bigint not null generated by default as identity,
    name varchar(50),
    primary key (id),
    unique (name)
);
create table user_role
(
    user_id bigint,
    role_id bigint,
    foreign key (user_id)
        references users,
    foreign key (role_id)
        references roles,
    primary key (user_id, role_id)
);
